version: "3.8"
services:
  rstudio:
    image: docker-id/docker-image:latest
    build:
      context: docker
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=pw
      - DISABLE_AUTH=false
    volumes:
      - .:${CONTAINER:-/home/rstudio/rproject}